### ISSUE TITLE
issues with MTEX2Prisms

### ISSUE THREAD

**Issue by Diego8901** [DorianDepriester/MTEX2Gmsh#11]
Dear Prof. Depriester,

I am trying to use MTEX2prisms to mesh my EBSD data. However, I see a lot of warnings when running the following lines in matlab:

V=grains_Sub_filled.V;
ori = min(V);
grains_Sub_filled.V = V-repmat(ori,size(grains_Sub_filled.V,1),1);
G = gmshGeo(grains_Sub_filled);
G=simplify(G);
max(grains_Sub_filled.V)
mesh(G,'mesh.msh','ElementType','HexOnly','GrainPrefix','','thickness',1);
exportGrainProps(G,'orientations_Ti2.txt','PRISMS')

Warning: wrong control point index in bspline.
Warning: No parametric coordinate on node XXXXX classified on curve XXXXX. 

![matlab_error message](https://user-images.githubusercontent.com/51404285/123951069-f31e2580-d9d6-11eb-9252-ec54ee79a997.jpg)

The generated mesh looks a little weird (see attached figures).

![mesh](https://user-images.githubusercontent.com/51404285/123951152-0fba5d80-d9d7-11eb-80e6-38f2eebe7b5b.jpg)
![mesh_magnified view](https://user-images.githubusercontent.com/51404285/123951157-121cb780-d9d7-11eb-8e1c-ab95cd0cb920.jpg)

I  run prisms-plasticity using this mesh as an input and it reports "Unable to open eulerDataFile".

![prisms_error message](https://user-images.githubusercontent.com/51404285/123951334-41332900-d9d7-11eb-9c06-45213fb64b96.jpg)

The matlab code and the EBSD file are also attached for your convenience.

I am using matlab R2020a, MTEX 5.7.0 (and 5.5.0), gmsh-4.8.4-Windows64, 

Thanks in advance.

Best,

Jie

[mesh_EBSD.txt](https://github.com/DorianDepriester/MTEX2Gmsh/files/6740387/mesh_EBSD.txt) (.m file)
[Scan1.txt](https://github.com/DorianDepriester/MTEX2Gmsh/files/6740394/Scan1.txt) (.ang file)

**Comment by DorianDepriester** [comment]
Hello Jie,
Those invading warning usually occur because the mesh has bad-quality elements. You can avoid those warning by turning off verbosity:

    mesh(...,'verbosity',0);

Those bad-quality elements can make PRISMS-Plasticity to crash. The only option I know it to play with the element sizes, e.g.:

    mesh(...,'ElementSize',2,'gradient',0.5);

Before running PRISMS-Plasticity, check out the stats about the element quality. In Gmsh, click on Tools > Statistics, then [Update]:
![image](https://user-images.githubusercontent.com/7643875/123959465-7c6d3200-d9ae-11eb-8c5f-825464ca576c.png).

But in your case, I suspect a wrong filename for the orientation file (according to the error you report). Are you sure you have

    set Orientations file name = orientations_Ti2.txt

in prm_Ti.prm?

Regards

**Comment by Diego8901** [comment]
Dear Prof. Depriester,

Thanks for your quick reply and the detailed instruction on checking the stats.

I just double checked the file name. It is correct.

Here is the mesh quality data I got. Looks it is not very much different from the one you have.
![mesh_quality](https://user-images.githubusercontent.com/51404285/123968767-1ef6d680-d9ea-11eb-90f1-c86a661ff0c7.jpg)

I will try, as you kindly suggested, tweaking the  "ElementSize" around the step size of the EBSD data (1 micron in my case). Do you have any idea (maybe rule of thumb) about the possible range of the "ElementSize" and the "gradient"?

Best,

Jie

**Comment by DorianDepriester** [comment]
As you can see, it seems that your mesh has elements with higher qualities than mine, so I guess the stats you showed are OK. 

Does ``orientations_Ti2.txt`` looks like this
````
GrainID	r_x	r_y	r_z	PhaseID
1	-29.1694005917162	-7.14651094712392	9.1602318239469	1
2	4.95209420216832	0.171016904396571	-1.12216662032698	1
3	-6.26206471634097	-24.4413571776647	4.52089251680632	1
4	-49.3313457627514	-11.8268070456472	15.3123305741446	1
5	3.36464042123366	-2.24077645914421	-0.140258234641589	1
6	3.97431365145908	-0.586452859500999	-0.12745803697512	1
7	-0.655102062645144	-2.95684457522837	0.842073714660126	1
8	27.7029531847048	17.0329782107541	-13.8039098729101	1
9	1.32377899681718	-3.57009860105265	1.22546265946082	1
10	-0.668313848591941	-4.1356439715152	0.450792195909747	1
11	1.88849506728168	-5.11508540007397	2.06689379973358	1
12	-2.93343570688579	-5.60339592476967	0.834553307365394	1
13	-25.8879803438331	-5.91557226932851	8.62979268769806	1
14	5.24327150974581	23.5611224377307	-7.1131308683806	1
15	3.59532148793841	-0.538646273024157	-0.493741256106927	1
16	9.41782174621558	-0.0272527354494938	-3.17365218359921	1
17	3.84731531667319	-2.8833671107099	-0.578796287224831	1
````
?

**Comment by DorianDepriester** [comment]
I have looked at the script file you sent. I think you should clean up your data before trying to mesh it. Here is an example procedure:
````
[grains, ebsd.grainId] = calcGrains(ebsd('indexed'),'angle',5*degree);
ebsd_clean=ebsd;
ebsd_clean(grains(grains.grainSize<=20)) = [];
[grains,ebsd_clean('indexed').grainId] = calcGrains(ebsd_clean('indexed'),'angle',5*degree);
ebsd_Sub_filled = ebsd;
grains_Sub_filled = grains;
````
(change the minimum size with respect to your wishes and replace your whole clean-up section by the  lines above)
This will result in 343 grains, instead of 1172.

Then, proceed as you did in your script. I have tried to run a simulation, and there is no issue about it... except that I suggest changing the element size (as mentioned before) in order to reduce the number of nodes. As is, the mesh contains 1.31e6 nodes, that is ~4e6 DoFs. Hence it will take WEEKS for a complete simulation.

If you want, I can send you all the input files I have used for the aforementioned test on PRISMS-Plasticity.

**Comment by Diego8901** [comment]
Dear Prof. Depriester,

Thanks for the suggestion on denoising the EBSD data.

Seems the problems are solved. I thought the failure of the prisms-plasticity was related to the warnings shown in matlab, but as you speculated, it is related to the readability of some files. More specifically, it turns out that the failure in prisms-pasticity was due to the denied permission of some files while running the prisms-plasticity (sorry about the mistake). 

I would be appreciated if you could kindly share your input files, or maybe a package including all the files and scripts that you used in the MTEX2Gmsh and prisms-plasticity.   This could help beginners like me to start from EBSD data to running the prisms-plasticity. (The manual MTEX2prisms.pdf is well written, but having an application example would be always helpful)

Thanks and regards.

Jie

**Comment by DorianDepriester** [comment]
Ji,
Glad to know everything works well now. As you suggest, I will provide ASAP a minimum working example containing all the materials for running a simulation on PRISMS-plasticity from EBSD data.
Regards.

**Comment by DorianDepriester** [comment]
Hello @Diego8901,
  As promised, I have created an example folder, containing all necessary materials for PRISMS-Plasticity.
Check it out [here](https://github.com/DorianDepriester/MTEX2Gmsh/tree/master/MTEX2prisms/Example)!

Also, be warned that I have recently fixed a bug in the ``exportGrainProps`` function, so you might update MTEX2Gmsh before keeping on.

Regards.
