### ISSUE TITLE
Image meshing 

### ISSUE THREAD

**Issue by Abdallahyoussef** [DorianDepriester/MTEX2Gmsh#12]
Hello, 
This tool is very interesting. However, I'd like to know if I can use the tool to mesh images (not necessary coming from EBSD).
It would be helpful if ones can read an image (e.g. imread('')), then mesh it based on colors.
I've an image (attached) and I want to know if I someone can help me to do so.

Thanks  

![REV_XZ_Filled_300](https://user-images.githubusercontent.com/48792950/124207080-fdc6e080-dae4-11eb-95da-5953f0f77b7a.jpg)

**Comment by DorianDepriester** [comment]
Hello,
Maybe you should have a look at [Im2mesh](https://fr.mathworks.com/matlabcentral/fileexchange/71772-im2mesh-2d-image-to-triangular-meshes).
Nevertheless, It is worth mentioning that EBSD maps coloured according to the Inverse Pole Figure convention does not provide sufficient informations for computing the local orientations. Indeed, even if you manage to compute the local crystal directions going outward the figure, you will still miss an angle for full definition of Euler Angles.

As a result, you need *at least* two figures with different colormaps (e.g. one coloured wrt. the outward direction and another coloured wrt. the vertical direction). In this case, you will even have redundant informations (4 angles instead of 3); thus, a not-that-straightforward error-minimizing technique should be used.

Those two issues are precisely the motivations behind the present project: working with EBSD data rather than *images* of EBSD data.

Regards
