### ISSUE TITLE
how to plot the output from Quadrature file.

### ISSUE THREAD

**Issue by rajesh-khatirkar** [DorianDepriester/MTEX2Gmsh#13]
Dear Dorian,

Thank you for creating such a nice toolbox.  I created the gmsh and orientation file for input using the MTEX2Gmsh toolbox.

I ran some simulations. The output is the Quadrature file. I have now the x, yz, r_x,r_y and r_z as output. I wish to plot it.

(1) Is there any possibility of plotting it directly or I have to convert it to Bunge angles first.
(2) I suppose its unstructured mesh. So I should use paraview or some other software.

Regards
Rajesh

**Comment by DorianDepriester** [comment]
Hello Rajesh,
I have written a small function for reading Quadrature outputs files and converting those data in MTEX's EBSD format (see [here](https://github.com/DorianDepriester/MTEX2Gmsh/blob/master/MTEX2prisms/ebsd_from_QuadratureOutputs.m)), so that you can easily plot the results. Indeed, since we use an unstructured mesh, the EBSD map will appear somehow sparse. Consider using the [fill](https://mtex-toolbox.github.io/EBSDFilling.html) function from MTEX if needed.
Also, have a look on the cavehat (mentioned in the help section) if your quadrature output files are too large files.

Regards.

**Comment by rajesh-khatirkar** [comment]
Thanks Dorian,

You have taken care of NaN also. .

Another question, Possibly you are using Prisms. 

When you use 2D data, how large a strain you can give? For example, if you want to do plane strain compression, upto what strain you can get reliable results. I am getting strange stress strain curves at large strains.

Regards
Rajesh

**Comment by DorianDepriester** [comment]
I have no idea how large the strain can be. You will for sure have issues in compression if your elements are too distorted. The only workaround I know is remeshing; but AFAIK, this feature is not (yet) available in Prism-plasticity. Also note that full-hex mesh (required by PRISMS-Plasticity) inevitably results in some poor-quality elements (see for instance the stats in Gmsh); if those elements are heavily distorted, this can lead to unrealistic results. 

Maybe have a look on [FEPX](https://fepx.info/), which does support remeshing. Note that MTEX2Gmsh can be used for FEPX as well, but the latter only works with tetrahedral elements, which is obviously not the best choice for 2D problems.

Regards.
