### ISSUE TITLE
medium with an ODF reflecting the bulk texture

### ISSUE THREAD

**Issue by Diego8901** [DorianDepriester/MTEX2Gmsh#19]
Dear Dorian,

I would like to perform Prism-Platicity CPFEM on an EBSD image. To simulate the fact that the area of interest is embed in a polycrystalline medium, I am wondering if the code could generate meshes for an EBSD image and then surround this area of interest with a "buffer layer" comprising grains with each grain represented by a single element. The orientations of  these single-element grains in the "buffer layer" are assigned so that they reflect the bulk texture of the material.

Thanks and regards,
Diego

**Comment by DorianDepriester** [comment]
Hello Diego,
Have you looked at the [`medium`](https://doriandepriester.github.io/MTEX2Gmsh/html/custom.html#3) option in the `mesh` command? This option was actually designed to implement an homogenized behavior in the surrounding medium (not a element-wise behavior). AFAIK, PRIMS-plasticity only works with CP behavior, hence it is impossible to define a stress-strain behavior. Hence, here a two possible approaches:

1. Write a small script which first pick random orientations from your ODF (see [MTEX doc](https://mtex-toolbox.github.io/RandomSampling.html) for that), then allocate these orientations to each elements in the medium.
2. Estimate the homogenized behavior first, then apply it to the medium. This can be done by FEM or FFT simulations. You can also use a Sachs model, as I have done in [1]. You will have to hard-code the homogenized behavior in PRISMS-Plasticity source code.

I think method 2 is the best option because method 1 can lead to unrealistic stress concentration a the medium/RoI interface. In addition, you will have to perform several simulations with different random orientations in order to ensure that the overall behavior you get is independent of these orientations. Nevertheless, method 2 requires advanced knowledge in C++ programming.

[1] https://doi.org/10.1016/j.ijplas.2023.103695

**Comment by Diego8901** [comment]
Dear Dorian,

Thanks for the reply. I was actually talking about method 1 (dont need C++ programming). I know how to extract the discrete orientations from a specific ODF, but dont know how to "allocate these orientations to each element in the medium. Do you have any idea how to achieve this?

Regards,
Diego

**Comment by DorianDepriester** [comment]
Hello Diego,
Sorry for the delay, I have just come back from vacation. The method 1 is actually not as easy as it sounds, because it requires some knowledge about scripting language (like Python) plus understanding how msh files are structured. Indeed, you need to create physical groups for each element in your medium, whereas physical groups are usually associated with geometrical entities (e.g. surfaces, volumes), not elements, in Gmsh. Hence the need to edit the msh file afterward.
I will try to investigate this in the next few days.

**Comment by DorianDepriester** [comment]
Hello @Diego8901,
Please, find [here](https://github.com/DorianDepriester/MTEX2Gmsh/blob/master/docs/Examples/twins_with_random_medium.m) a possible partial implementation of your approach.

I think the easiest to do this is indeed to create dummy grains around your region of interest, and treat these grains a normal grains in MTEX2Gmsh. To do this, I just create random orientations (picked from the ODF) at random locations in the medium.

The image bellow illustrates the differences between the granular geometry we have initially (left) and the geometry we get with dummy EBSD data in the medium (right).
![image](https://github.com/DorianDepriester/MTEX2Gmsh/assets/7643875/76a1bf69-d8fa-42fa-9f8f-0143175b1937)

**Comment by Diego8901** [comment]
Dear Dorian,

Thanks so much for your solution. Actually I was doing similar things. As shown below, I created a medium with each pixel having unique orientations (discrete orientations from ODF as you did). 
I am wondering if having more/small "grains" in the medium would be helpful to avoid the "unrealistic stress concentration" problem you mentioned earlier.

![1693554464670](https://github.com/DorianDepriester/MTEX2Gmsh/assets/51404285/9e9ebba7-e25c-4138-a91c-ed17cc13054d)

BTW, is it possible to have this type of fake medium above and below the area of interest?

Best regards,
Diego

**Comment by DorianDepriester** [comment]
Wow, that's a lot of elements!
Obviously, the larger the number of elements, the less likely you are to have odd stress concentration. But maybe you should try to slightly  reduce your number of elements :thinking:
I don't think it would be easy to add such kind of fake medium *below* the RoI because MTEX2Gmsh does not handle 3D EBSD.

**Comment by Diego8901** [comment]
You are right, Dorian! 

I certainly have to reduce the number of element, but do you have any recommendations on the size of the medium (I mean maybe there is a recommended ratio between the width of the medium and that of the AOI) so that we can largely avoid the odd stress concentration and maintain an acceptable calculation efficiency?
