### ISSUE TITLE
quality of the mesh

### ISSUE THREAD

**Issue by Diego8901a** [DorianDepriester/MTEX2Gmsh#20]
Hi Dorian,

Do you have any recommendations on the acceptable mesh quality for Prism-plasticity. Any rule of thumb on the "threshold" values of SICN, Gamma, and SIGE? How good is good enough?

Many thanks,

Diego

**Comment by DorianDepriester** [comment]
Hello Diego,
Unfortunately I have no recommandation about threshold values, and I know it is pain to get an acceptable mesh for PRISMS-Plasticity. This is because we use `HexOnly`, resulting in some highly distorted element highly distorted (usually near triple junctions). Here is the quality values I get on mesh I use in PRISMS-Plasticity (and it works):
![image](https://github.com/DorianDepriester/MTEX2Gmsh/assets/7643875/4164d22a-5706-4711-9a48-9854ee2416aa)

If you really do not manage to get a proper mesh, avoid the `gradient` option.

**Comment by Diego8901a** [comment]
Thanks Dorian!

Avoiding gradient option works!

Diego
